---
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# Use the new container infrastructure
sudo: false

# Install ansible
install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/