---
language: python
sudo: required

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-openresty daixijun.openresty
  - cd daixijun.openresty

install:
  - pip install ansible molecule docker

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
