---
- name: Set openresty yum repository
  yum_repository:
    name: openresty
    description: Official OpenResty Open Source Repository for CentOS
    enabled: yes
    baseurl: https://openresty.org/package/centos/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://openresty.org/package/pubkey.gpg
    state: present
  diff: true
  tags:
    - always

- name: Ensure openresty is installed
  yum:
    name: openresty,openresty-resty,openresty-opm
    state: present
    autoremove: true
    update_cache: true
  tags:
    - install

- name: Ensure nginx group exists
  group:
    name: nginx
    system: yes
    state: present
  tags:
    - user

- name: Ensure nginx user exists
  user: 
    name: nginx 
    shell: /sbin/nologin 
    home: /var/cache/nginx 
    system: yes 
    group: nginx 
    move_home: yes 
    state: present
  tags:
    - user

- name: Create openresty directorys
  file:
    path: '{{ item }}'
    state: directory
    owner: nginx
    group: nginx
  loop:
    - '{{ openresty_log_path }}'
