---
- name: Set openresty yum repository
  yum_repository:
    name: openresty
    description: Official OpenResty Open Source Repository for CentOS
    enabled: yes
    baseurl: https://openresty.org/package/centos/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://openresty.org/package/pubkey.gpg
    state: presnet
  diff: true
  tags:
    - always

- name: Ensure openresty is installed
  yum:
    name: openresty,openresty-resty,openresty-opm
    state: present
    autoremove: true
    update_cache: true
  tags:
    - install

- name: Create openresty directorys
  file:
    path: '{{ item }}'
    state: directory
    owner: nginx
    group: nginx
  loop:
    - '{{ openresty_log_path }}'
