---
- name: Set openresty yum repository
  yum_repository:
    name: openresty
    description: Official OpenResty Open Source Repository for CentOS
    enabled: yes
    baseurl: https://openresty.org/package/centos/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://openresty.org/package/pubkey.gpg
    state: present
  tags:
    - always

- name: Ensure openresty is installed
  yum:
    name: openresty,openresty-resty,openresty-opm
    state: present
    update_cache: true
  tags:
    - install

- name: Ensure {{ openresty_user }} group exists
  group:
    name: "{{ openresty_user }}"
    system: yes
    state: present
  tags:
    - user

- name: Ensure {{ openresty_user }} user exists
  user:
    name: "{{ openresty_user }}"
    shell: /sbin/nologin
    home: /var/cache/nginx
    system: yes
    group: "{{ openresty_user }}"
    move_home: yes
    state: present
  tags:
    - user

- name: Create openresty directorys
  file:
    path: "{{ item }}"
    state: directory
    recurse: false
    owner: "{{ openresty_user }}"
    group: "{{ openresty_user }}"
  loop:
    - "{{ openresty_log_path }}"
    - /usr/local/openresty/nginx/conf/vhost.d/
    - /usr/local/openresty/nginx/conf/certs/
    - /usr/share/nginx/

- name: Create nginx.conf
  template:
    src: nginx.conf.j2
    dest: /usr/local/openresty/nginx/conf/nginx.conf
    lstrip_blocks: True
    validate: /usr/local/openresty/nginx/sbin/nginx -t -c %s
  notify:
    - restart openresty
  tags:
    - config

- name: Create managed default server configuration file
  template:
    src: default.conf.j2
    dest: /usr/local/openresty/nginx/conf/vhost.d/default.conf
    lstrip_blocks: True
  notify:
    - restart openresty
  tags:
    - config

- name: Create managed virtual host configuration files
  template:
    src: vhost.conf.j2
    dest: /usr/local/openresty/nginx/conf/vhost.d/{{ item.filename|default(item.server_name) }}.conf
    lstrip_blocks: True
  when: item.state|default('present') == 'present'
  loop: "{{ openresty_vhosts }}"
  notify:
    - restart openresty
  tags:
    - config

- name: Remove managed virtual host configuration files
  file:
    path: /usr/local/openresty/nginx/conf/vhost.d/{{ item.filename|default(item.server_name) }}.conf
    state: absent
  when: item.state|default('present') == 'absent'
  loop: "{{ openresty_vhosts }}"
  notify:
    - restart openresty
  tags:
    - config

- name: Create ssl certificate
  copy:
    src: "{{ item.ssl_certificate }}"
    dest: "/usr/local/openresty/nginx/conf/certs/{{ item.server_name }}.cert.pem"
  when:
    - openresty_vhosts is defined
    - openresty_vhosts|length > 0
    - item.enable_ssl is defined
    - item.enable_ssl | default(false)
    - item.ssl_certificate is defined
  loop: "{{ openresty_vhosts }}"
  notify:
    - restart openresty

- name: Create ssl certificate key
  copy:
    src: "{{ item.ssl_certificate_key }}"
    dest: "/usr/local/openresty/nginx/conf/certs/{{ item.server_name }}.key.pem"
  when:
    - openresty_vhosts is defined
    - openresty_vhosts|length > 0
    - item.enable_ssl is defined
    - item.enable_ssl | default(false)
    - item.ssl_certificate_key is defined
  loop: "{{ openresty_vhosts }}"
  notify:
    - restart openresty

- name: Startup systemd service
  copy:
    src: openresty.service
    dest: /usr/lib/systemd/system/openresty.service
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version|int >= 7
  notify:
    - restart openresty
