---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -xe
  yamllint .
  ansible-lint .
platforms:
  - name: openresty
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
    - --vault-password-file=.vault.txt
verifier:
  name: ansible
